### ISSUE TITLE
doesn't work 😕

### ISSUE THREAD

**Issue by ziofil** [alexhyett/traefik-vs-nginx-docker#1]
I follow the instructions to the letter (for Traefik without SSL), but it doesn't work: safari does't find http://localhost/whoami
I'm on macOS Big Sur, ssh-ing into an rpi4 in the home wifi network.

**Comment by alexhyett** [comment]
If you are ssh-ing into your rpi and you want to access it from another computer on your network you need to use the IP address of your rpi. So if your rpi has an IP address of a a 192.168.1.20 then you should be able to access whoami from http://192.168.1.20/whoami.

Localhost will always reference the computer you are on, I should probably make that clearer in the docs.

**Comment by ziofil** [comment]
Oh, right, of course. I see whoami now. But I cannot access other services. Am I not configuring them well? Here's an example:
```yml
 homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /home/pi/homeassistant/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homeassistant.rule=PathPrefix(`/homeassistant{regex:$$|/.*}`)'
      - 'traefik.http.services.homeassistant.loadbalancer.server.port=80'
    networks:
      - pi
```
the traefik dashboard shows it's up, but it has a weird IP (and I can't access it)
<img width="1008" alt="Screen Shot 2021-03-20 at 5 26 21 PM" src="https://user-images.githubusercontent.com/8944955/111885978-64dee000-89a1-11eb-8b05-16428246743c.png">
if I go to `http://\<rpi4 ip\>/homeassistant I get a web page with "Bad Gateway" written on it.

**Comment by alexhyett** [comment]
So looking at the [home assistant docs](https://www.home-assistant.io/installation/raspberrypi#raspberry-pi-4) there are a few things wrong with your setup.

Home Assistant runs on port `8123` instead of port `80`. You also need to specify where to mount the config directory in the container.

Your setup should probably look something like this:

```yml
 homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:stable
    volumes:
      - /home/pi/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homeassistant.rule=PathPrefix(`/homeassistant{regex:$$|/.*}`)'
      - 'traefik.http.services.homeassistant.loadbalancer.server.port=8123'
    networks:
      - pi
```

As there isn't an issue with this repository I am going to close this issue. If you need any help getting home assistant setup they have a few channels you can get help on https://www.home-assistant.io/help/
